Controllers/DGMLController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;
using DGMLD3.Data;
using DGMLD3.Data.CONTEXT;
using DGMLD3.Data.DTO;
using DGMLD3.Data.RDMS;
using DGMLD3.Data.VIEW;
using DGMLD3.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Distributed;
using Newtonsoft.Json;

namespace DGMLD3.Controllers
{
    public class DGMLController : BaseController
    {
        private readonly GraphRedisService _graphRedisService;

        public DGMLController(ApplicationDbContext context, 
            GraphRedisService graphRedisService, UserManager<ApplicationUser> userManager)
            :base(context, userManager)
        {
            _graphRedisService = graphRedisService;
        }

        public IActionResult Upload()
        {
            UploadViewModel model = new UploadViewModel();

            return View(model);
        }

        [HttpPost] 
        public async Task<IActionResult> Upload(UploadViewModel model)
        {
            var fileName = Path.GetFileName(model.file.FileName);
            if(Path.GetExtension(fileName).Equals(".dgml")){
                try
                {
                    using var uploadedFile = model.file.OpenReadStream();
                    (List<GraphNodeDTO> nodes, List<GraphLinkDTO> links) = GraphMapperService.GenerateD3Network(uploadedFile, model.DGML_Type_ID);

                    Graph newGraph = GraphMapperService.MapToNewGraphInDB(nodes, links);
                    newGraph.ReadableName = model.GraphName;
                    string LINK_URL = "/DGML/ViewNetwork?graphName=" + newGraph.Name;
                    newGraph.GraphLinkURL = LINK_URL;
                    var user = await _userManager.GetUserAsync(HttpContext.User);
                    newGraph.Creator = user;
                    _context.Graphs.Add(newGraph);
                    await _context.SaveChangesAsync();

                    string NODES = JsonConvert.SerializeObject(nodes);
                    string LINKS = JsonConvert.SerializeObject(links);

                    ViewBag.NODES = NODES;
                    ViewBag.LINKS = LINKS;

                    //await _graphRedisService.SaveGraphToCache(newGraph);

                    ViewBag.LINK_URL = "https://" + Request.Host.Value + LINK_URL;
                }
                catch (Exception error)
                {
                    Console.WriteLine(error.Message);
                    model.ErrorMsg = "Could not read file";
                    return View("Upload", model);
                }
               
            }
            else
            {
                model.ErrorMsg = "Please Enter a valid .dgml";
                return View("Upload", model);
            }
            
            return View("Network");
        }


        [HttpGet]
        public async Task<IActionResult> ViewNetwork([FromQuery]string graphName)
        {
            var graph = await _context.Graphs.Where(x => x.Name.Equals(graphName)).FirstOrDefaultAsync();
            ViewBag.Graph_ID = graph.Id;
            ViewBag.LINK_URL = "https://" + Request.Host.Value + graph.GraphLinkURL;

            Graph fullGraph = await _context.Graphs.Where(x => x.Name.Equals(graphName)).FirstOrDefaultAsync();
            (List<GraphNodeDTO> nodes, List<GraphLinkDTO> links) = GraphMapperService.MapGraphToDTOs(fullGraph);
            ViewBag.NODES = JsonConvert.SerializeObject(nodes);
            ViewBag.LINKS = JsonConvert.SerializeObject(links);
            return View("Network");

        }
    }
}

Controllers/GraphsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using DGMLD3.Data.CONTEXT;
using DGMLD3.Data.RDMS;
using DGMLD3.Data.VIEW;
using Microsoft.AspNetCore.Identity;

namespace DGMLD3.Controllers
{
    [Authorize]
    public class GraphsController : BaseController
    {
       
        public GraphsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager):base(context, userManager)
        {
        }

        // GET: Graphs
        public async Task<IActionResult> Index()
        {
            GraphTableViewModel vm = new GraphTableViewModel();
            ApplicationUser user = await GetCurrentUser();
            vm.Graphs = await _context.Graphs.Where(s => s.Creator.Id.Equals(user.Id)).ToListAsync();
            return View(vm);
        }

        // GET: Graphs
        public async Task<IActionResult> Search([FromQuery] string SearchString)
        {
            GraphTableViewModel vm = new GraphTableViewModel();
            ApplicationUser user = await GetCurrentUser();
            vm.Graphs = await _context.Graphs.Where(s => s.Creator.Id.Equals(user.Id)).ToListAsync();
            return View(vm);
        }



        // GET: Graphs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var graph = await _context.Graphs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (graph == null)
            {
                return NotFound();
            }

            return View(graph);
        }

        // GET: Graphs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var graph = await _context.Graphs.FindAsync(id);
            if (graph == null)
            {
                return NotFound();
            }
            return View(graph);
        }

        // POST: Graphs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ReadableName,IsPublic")] Graph graph)
        {
            if (id != graph.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var curGraph = await _context.Graphs.Where(x => x.Id == graph.Id).FirstOrDefaultAsync();
                    curGraph.ReadableName = graph.ReadableName;
                    curGraph.IsPublic = graph.IsPublic;
                    //_context.Update(graph);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GraphExists(graph.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(graph);
        }

        // GET: Graphs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var graph = await _context.Graphs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (graph == null)
            {
                return NotFound();
            }

            return View(graph);
        }

        // POST: Graphs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var graph = await _context.Graphs.FindAsync(id);
            _context.Graphs.Remove(graph);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GraphExists(int id)
        {
            return _context.Graphs.Any(e => e.Id == id);
        }
    }
}

Controllers/PricingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DGMLD3.Data;
using Microsoft.AspNetCore.Authorization;
using DGMLD3.Data.CONTEXT;
using DGMLD3.Data.RDMS;

namespace DGMLD3.Controllers
{
    [Authorize(Roles ="Admin")]
    public class PricingController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PricingController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pricing
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var plans = await _context.PricePlans.Where(x => x.IsActive == true).OrderBy(x => x.Id).ToListAsync();
            return View(plans);
        }

        // GET: Pricing/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pricing = await _context.PricePlans
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pricing == null)
            {
                return NotFound();
            }

            return View(pricing);
        }

        // GET: Pricing/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pricing/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,ChargeAmount,Features,BillingPer,IsActive")] PricePlan pricing)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pricing);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pricing);
        }

        // GET: Pricing/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pricing = await _context.PricePlans.FindAsync(id);
            if (pricing == null)
            {
                return NotFound();
            }
            return View(pricing);
        }

        // POST: Pricing/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ChargeAmount,Features,BillingPer,IsActive")] PricePlan pricing)
        {
            if (id != pricing.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pricing);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PricingExists(pricing.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pricing);
        }

        // GET: Pricing/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pricing = await _context.PricePlans
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pricing == null)
            {
                return NotFound();
            }

            return View(pricing);
        }

        // POST: Pricing/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pricing = await _context.PricePlans.FindAsync(id);
            _context.PricePlans.Remove(pricing);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PricingExists(int id)
        {
            return _context.PricePlans.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <title>DGMLConverter.net</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Easily convert from your DGML file generated by Visual Studio to a shareable link">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.5.2/cerulean/bootstrap.min.css" integrity="sha512-po2m5Mh7JX6GSmbR8hPZT3Yc86zc9OQts1s65kBneL2ZgVBKcMHvzcBhasVCefF0V9CNXQcxgVimw9yI+DlGVg==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/AlertifyJS/1.11.4/css/alertify.min.css" integrity="sha256-HyknUQX006D7lC1CzL2BQqMMjX7cQV7unnkuNrYUDgM=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/AlertifyJS/1.11.4/css/themes/bootstrap.min.css" integrity="sha256-tWRKenfvuraOz4u9wNIkJVrUFbRN712r9WtYhGUPirg=" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DGMLD3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Graphs" asp-action="Index">Your Graphs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DGML" asp-action="Upload">Get Started</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pricing" asp-action="Index">Pricing</a>
                        </li>*@

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DGMLD3
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/AlertifyJS/1.11.4/alertify.min.js" integrity="sha256-TmZbMuBl7X3riNkZNRGGFWfpltDc50OK5Kzj4UrtvuE=" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script defer src="https://www.avaanalytics.com/js/prod/count.min.js" data-sharpcounter="https://www.avaanalytics.com/api/Interaction/Count"
            data-sharpcounter-apikey="9d0e6d7a-bec3-45bd-a378-4b458aed16a7"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>