Controllers/DGMLController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;
using DGMLD3.Data;
using DGMLD3.Data.CONTEXT;
using DGMLD3.Data.DTO;
using DGMLD3.Data.RDMS;
using DGMLD3.Data.VIEW;
using DGMLD3.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Distributed;
using Newtonsoft.Json;

namespace DGMLD3.Controllers
{
    public class DGMLController : BaseController
    {
        private readonly GraphRedisService _graphRedisService;

        public DGMLController(ApplicationDbContext context, 
            GraphRedisService graphRedisService, UserManager<ApplicationUser> userManager)
            :base(context, userManager)
        {
            _graphRedisService = graphRedisService;
        }

        public IActionResult Upload()
        {
            UploadViewModel model = new UploadViewModel();

            return View(model);
        }

        [HttpPost] 
        public async Task<IActionResult> Upload(UploadViewModel model)
        {
            var fileName = Path.GetFileName(model.file.FileName);
            if(Path.GetExtension(fileName).Equals(".dgml")){
                try
                {
                    using var uploadedFile = model.file.OpenReadStream();
                    (List<GraphNodeDTO> nodes, List<GraphLinkDTO> links) = GraphMapperService.GenerateD3Network(uploadedFile, model.DGML_Type_ID);

                    Graph newGraph = GraphMapperService.MapToNewGraphInDB(nodes, links);
                    newGraph.ReadableName = model.GraphName;
                    string LINK_URL = "/DGML/ViewNetwork?graphName=" + newGraph.Name;
                    newGraph.GraphLinkURL = LINK_URL;
                    var user = await _userManager.GetUserAsync(HttpContext.User);
                    newGraph.Creator = user;
                    _context.Graphs.Add(newGraph);
                    await _context.SaveChangesAsync();

                    string NODES = JsonConvert.SerializeObject(nodes);
                    string LINKS = JsonConvert.SerializeObject(links);

                    ViewBag.NODES = NODES;
                    ViewBag.LINKS = LINKS;

                    //await _graphRedisService.SaveGraphToCache(newGraph);

                    ViewBag.LINK_URL = "https://" + Request.Host.Value + LINK_URL;
                }
                catch (Exception error)
                {
                    Console.WriteLine(error.Message);
                    model.ErrorMsg = "Could not read file";
                    return View("Upload", model);
                }
               
            }
            else
            {
                model.ErrorMsg = "Please Enter a valid .dgml";
                return View("Upload", model);
            }
            
            return View("Network");
        }


        [HttpGet]
        public async Task<IActionResult> ViewNetwork([FromQuery]string graphName)
        {
            var graph = await _context.Graphs.Where(x => x.Name.Equals(graphName)).FirstOrDefaultAsync();
            ViewBag.Graph_ID = graph.Id;
            ViewBag.LINK_URL = "https://" + Request.Host.Value + graph.GraphLinkURL;

            Graph fullGraph = await _context.Graphs.Where(x => x.Name.Equals(graphName)).FirstOrDefaultAsync();
            (List<GraphNodeDTO> nodes, List<GraphLinkDTO> links) = GraphMapperService.MapGraphToDTOs(fullGraph);
            ViewBag.NODES = JsonConvert.SerializeObject(nodes);
            ViewBag.LINKS = JsonConvert.SerializeObject(links);
            return View("Network");

        }
    }
}

Controllers/GraphsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using DGMLD3.Data.CONTEXT;
using DGMLD3.Data.RDMS;
using DGMLD3.Data.VIEW;
using Microsoft.AspNetCore.Identity;

namespace DGMLD3.Controllers
{
    [Authorize]
    public class GraphsController : BaseController
    {
       
        public GraphsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager):base(context, userManager)
        {
        }

        // GET: Graphs
        public async Task<IActionResult> Index()
        {
            GraphTableViewModel vm = new GraphTableViewModel();
            ApplicationUser user = await GetCurrentUser();
            vm.Graphs = await _context.Graphs.Where(s => s.Creator.Id.Equals(user.Id)).ToListAsync();
            return View(vm);
        }

        // GET: Graphs
        public async Task<IActionResult> Search([FromQuery] string SearchString)
        {
            GraphTableViewModel vm = new GraphTableViewModel();
            ApplicationUser user = await GetCurrentUser();
            vm.Graphs = await _context.Graphs.Where(s => s.Creator.Id.Equals(user.Id)).ToListAsync();
            return View(vm);
        }



        // GET: Graphs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var graph = await _context.Graphs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (graph == null)
            {
                return NotFound();
            }

            return View(graph);
        }

        // GET: Graphs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var graph = await _context.Graphs.FindAsync(id);
            if (graph == null)
            {
                return NotFound();
            }
            return View(graph);
        }

        // POST: Graphs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ReadableName,IsPublic")] Graph graph)
        {
            if (id != graph.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var curGraph = await _context.Graphs.Where(x => x.Id == graph.Id).FirstOrDefaultAsync();
                    curGraph.ReadableName = graph.ReadableName;
                    curGraph.IsPublic = graph.IsPublic;
                    //_context.Update(graph);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GraphExists(graph.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(graph);
        }

        // GET: Graphs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var graph = await _context.Graphs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (graph == null)
            {
                return NotFound();
            }

            return View(graph);
        }

        // POST: Graphs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var graph = await _context.Graphs.FindAsync(id);
            _context.Graphs.Remove(graph);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GraphExists(int id)
        {
            return _context.Graphs.Any(e => e.Id == id);
        }
    }
}

Controllers/LinksController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using DGMLD3.Data.CONTEXT;
using DGMLD3.Data.RDMS;
using DGMLD3.Data.VIEW;

namespace DGMLD3.Controllers
{
    [Authorize]
    public class LinksController : BaseController
    {

        public LinksController(ApplicationDbContext context, 
            UserManager<ApplicationUser> userManager):base(context, userManager)
        {
        }

        // GET: Links
        public async Task<IActionResult> Index(string currentGraphId)
        {
            var curUser = await GetCurrentUser();
            
            var graph = await _context.Graphs.Include(x => x.Creator)
                .Where(x => x.Id == Int32.Parse(currentGraphId) 
                && x.Creator.Id.Equals(curUser.Id)).FirstOrDefaultAsync();

            var links = graph.Links.ToList();

            LinkTableViewModel vm = new LinkTableViewModel
            {
                GraphName = graph.ReadableName,
                GraphLink = graph.GraphLinkURL,
                GraphId = graph.Id,
                Links = links
            };

            return View(vm);
        }

        // GET: Links
        public async Task<IActionResult> Search([FromQuery] string SearchString, [FromQuery] string currentGraphId)
        {
            LinkTableViewModel vm = new LinkTableViewModel();
            ApplicationUser user = await GetCurrentUser();
            var curUser = await GetCurrentUser();

            var graph = await _context.Graphs.Include(x => x.Creator)
                .Where(x => x.Id == Int32.Parse(currentGraphId)
                && x.Creator.Id.Equals(curUser.Id)).FirstOrDefaultAsync();

            var links = graph.Links.ToList();
            return View(vm);
        }
    }
}

Views/Graphs/Create.cshtml
@model Graph

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Graph</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Graphs/Delete.cshtml
@model Graph

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Graph</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Graphs/Details.cshtml
@model Graph

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Graph</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Unique Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Readable Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReadableName)
        </dd>
        <dt class="col-sm-2">
            Public URL
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GraphLinkURL)
        </dd>
        <dt class="col-sm-2">
            Date Created
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class="col-sm-2">
            Public
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsPublic)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Graphs/Edit.cshtml
@model Graph

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Graph</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label class="control-label">Name</label>
                <input asp-for="ReadableName" class="form-control" />
                <span asp-validation-for="ReadableName" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPublic" /> @Html.DisplayNameFor(model => model.IsPublic)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Graphs/Index.cshtml
@model GraphTableViewModel
<link href="https://unpkg.com/jquery-resizable-columns@0.2.3/dist/jquery.resizableColumns.css" rel="stylesheet">
<link href="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table.min.css" rel="stylesheet">
<h1>Your Graphs</h1>

<p>
    <a class="btn btn-primary" asp-controller="DGML" asp-action="Upload">Create New</a>
</p>
<form asp-action="Search" method="get">
    <div class="form-actions no-color">
        <div class="form-group">
            <label for="SearchString">Search:</label>
            <input type="text" name="SearchString" class="form-control" value="@Model.SearchString" />
        </div>
        <p>
            <input type="submit" value="Search" class="btn btn-primary" /> |
            <a class="btn btn-primary" asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>
<table id="table"
       data-toggle="table"
       data-height="700"
       data-pagination="true"
       class="table">
    <thead>
        <tr>
            <th data-field="ReadableName" data-sortable="true">
                Name
            </th>
            <th data-field="DateCreated" data-sortable="true">
                Date Created
            </th>
            <th data-field="IsPublic" data-sortable="true">
                Is Public
            </th>
            <th data-field="">
                Link To Graph Links
            </th>
            <th data-field="GraphLinkURL">
                Link To Graph
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Graphs.Count(); i++)
        {
            <tr id="tr-id-@i" class="tr-class-@i" data-title="bootstrap table" data-object='{"key": "value"}'>
                <td id="td-id-@i" class="td-class-@i" data-title="bootstrap table">
                    @Html.DisplayFor(modelItem => Model.Graphs[i].ReadableName)
                </td>
                <th>
                    @Html.DisplayFor(modelItem => Model.Graphs[i].DateCreated)
                </th>
                <th>
                    @if (Model.Graphs[i].IsPublic)
                    {
                        <i class="fas fa-check fa-3x" style="color:green;"></i>
                    }
                    else
                    {
                        <i class="far fa-times-circle fa-3x" style="color:red;"></i>
                    }
                   
                </th>
                <th>
                    <a asp-controller="Links" asp-action="Index" asp-route-currentGraphId="@Model.Graphs[i].Id">Link to Graph Links</a>
                </th>
                <th>
                    <a target="_blank" rel="noopener noreferrer" href="@Model.Graphs[i].GraphLinkURL">View Graph</a>
                </th>
                <td>
                    <a asp-action="Edit" asp-route-id="@Model.Graphs[i].Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@Model.Graphs[i].Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@Model.Graphs[i].Id">Delete</a> 
                </td>
            </tr>
        }

    </tbody>
</table>
@section Scripts{

    <script src="https://unpkg.com/jquery-resizable-columns@0.2.3/dist/jquery.resizableColumns.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.17.1/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.17.1/dist/extensions/resizable/bootstrap-table-resizable.min.js"></script>
    <script>
        $(function () {
            $('#table').bootstrapTable()
        })
    </script>
}